---
root_ca_certificate: |
  MIIE5DCCA8ygAwIBAgIUHBk9HjOFCPyihEpHkiwNaEV07zwwDQYJKoZIhvcNAQEL
  BQAwgZsxCzAJBgNVBAYTAkFVMQwwCgYDVQQIDANRTEQxETAPBgNVBAcMCEJyaXNi
  YW5lMRgwFgYDVQQKDA9EZW1vIENBIFB0eSBMdGQxFTATBgNVBAsMDERlbW8gQ0Eg
  VW5pdDEVMBMGA1UEAwwMRGVtbyBSb290IENBMSMwIQYJKoZIhvcNAQkBFhRyb290
  LWNhLTFAc2FtcGxlLmNvbTAeFw0yMzA3MTIxMjQzNDRaFw00MzAxMTgxMjQzNDRa
  MIGbMQswCQYDVQQGEwJBVTEMMAoGA1UECAwDUUxEMREwDwYDVQQHDAhCcmlzYmFu
  ZTEYMBYGA1UECgwPRGVtbyBDQSBQdHkgTHRkMRUwEwYDVQQLDAxEZW1vIENBIFVu
  aXQxFTATBgNVBAMMDERlbW8gUm9vdCBDQTEjMCEGCSqGSIb3DQEJARYUcm9vdC1j
  YS0xQHNhbXBsZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDK
  DKuI2jGdV9Pf7ZppckCjvHrH1uJlFOk1DJR3JZdGaNxTBFLYt+tRepnhETnC5Arj
  NwK23fN87sf4loZfLeoypP25c7jQU4zUtlJ/VS77z8b4Z7SSnaNjwNwEH91bWnEI
  5f2+2z+rMuijZeb8G6Z17EZ3XcZFJjQocyu+UWh0v2m+Qr+y82Pfyl0wiw/rEOPL
  2iimIXT9I3HyZOJF3H0lGroZB1Gvjrrc5i33iLkGMQmQkdlBTNdtNgzUMmu8SKWt
  HRwEK3+EujasJeAkEsnNroq07HYyhj3hjuh6X5Ftl4/5YI4gWaxBbeyumitr2wfN
  0jYvgho0zrwRVqAT25D7AgMBAAGjggEcMIIBGDAMBgNVHRMEBTADAQH/MB0GA1Ud
  DgQWBBR11WGLTns0xyCSz0Kqyn+WTRmCjzCB2wYDVR0jBIHTMIHQgBR11WGLTns0
  xyCSz0Kqyn+WTRmCj6GBoaSBnjCBmzELMAkGA1UEBhMCQVUxDDAKBgNVBAgMA1FM
  RDERMA8GA1UEBwwIQnJpc2JhbmUxGDAWBgNVBAoMD0RlbW8gQ0EgUHR5IEx0ZDEV
  MBMGA1UECwwMRGVtbyBDQSBVbml0MRUwEwYDVQQDDAxEZW1vIFJvb3QgQ0ExIzAh
  BgkqhkiG9w0BCQEWFHJvb3QtY2EtMUBzYW1wbGUuY29tghQcGT0eM4UI/KKESkeS
  LA1oRXTvPDALBgNVHQ8EBAMCAQYwDQYJKoZIhvcNAQELBQADggEBAIWY1Qf579Kr
  fp3rfAOmHOd+scV33wtODP9DTXljPcAUBMT3+N785xYYNGaOetGeBplFq0mzg3q6
  rqxWM7nA/9QKO7CmQoQxdf92+jG970nam1pj3eMdmqrhp4CaFrg8nMzJCBRd4WRu
  F+vpGzxpqaaECLtXg0mDWBTUtX52CIEZ/RNTwSKibBTFlxbU6uwTfKwlycb57+QJ
  RFel4Kx0Em9NFSd3gXv6qmWceA92j0G8mg5lFZE71sAdoouD7/XIFBH0d80Iooza
  DWIAIQYOoECje5usaoRrMd9ajk6NyPhdcBeail3C1TAFdMKAxKUsBcyZ2U0DG7hV
  yowCKpl20qQ=
