---
template:
  path: iam/role.yaml.j2

sceptre_user_data:
  project_code: {{stack_group_config.project_code}}
  source_repo_url: {{stack_group_config.source_repo_url}}
  roles:
    - name: RolesAnywhere1
      role_name: DemoRolesAnywhere1
      assume_role_policy_document: |
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - rolesanywhere.amazonaws.com
            Action:
              - sts:AssumeRole
              - sts:TagSession
              - sts:SetSourceIdentity
      description: IAM Role for ImageBuilderInstance
      managed_policy_arns:
        - arn:aws:iam::aws:policy/PowerUserAccess
      max_session_duration: 3600
