---
template:
  path: rolesanywhere/profile.yaml.j2

sceptre_user_data:
  project_code: {{stack_group_config.project_code}}
  source_repo_url: {{stack_group_config.source_repo_url}}
  profiles:
    - name: rolesanywhereprofiletest1
      profile_name: RolesAnywhereProfile1
      duration_seconds: 3600
      enabled: True
      require_instance_properties: false
      role_arns:
        - !stack_output {{pwd}}/iam-role.yaml::RolesAnywhere1Arn
      tags:
        Name: rolesanywhereprofiletest1
        Project: '{{stack_group_config.project_code}}'

stack_tags:
  Test: rolesanywhere-profile
