---
template:
  path: rolesanywhere/trust_anchor.yaml.j2

sceptre_user_data:
  project_code: {{stack_group_config.project_code}}
  source_repo_url: {{stack_group_config.source_repo_url}}
  trust_anchors:
    - name: rolesanywheretrustanchortest1
      trust_anchor_name: TrustAnchor1
      enabled: true
      source:
        source_type: CERTIFICATE_BUNDLE
        source_data:
          x509_certificate_data: {{var.root_ca_certificate}}
      tags:
        Name: rolesanywheretrustanchortest1
        Project: {{stack_group_config.project_code}}

stack_tags:
  Test: rolesanywhere-trustanchor
